*** empty log message ***

diff --git a/trunk/castor-2002/castor/src/etc/sourceGen b/trunk/castor-2002/castor/src/etc/sourceGen
--- a/trunk/castor-2002/castor/src/etc/sourceGen
+++ b/trunk/castor-2002/castor/src/etc/sourceGen
@@ -1,2 +1,20 @@
-java org.exolab.castor.builder.SourceGenerator $@
+#! /bin/sh
+
+# $Id$
+
+if [ -z "$JAVA_HOME" ] ; then
+  JAVA=`which java`
+  if [ -z "$JAVA" ] ; then
+    echo "Cannot find JAVA. Please set your PATH."
+    exit 1
+  fi
+  JAVA_BIN=`dirname $JAVA`
+  JAVA_HOME=$JAVA_BIN/..
+fi
+
+JAVA=$JAVA_HOME/bin/java
+
+CLASSPATH=`echo *.jar | tr ' ' ':'`:$CLASSPATH:.
+
+$JAVA -cp $CLASSPATH org.exolab.castor.builder.SourceGenerator $@
 
